<?php
$wapersons = array(
    "Adnan Amin" => ["languages" => "( English, Urdu, Hindi )", "phoneNumber" => "+971524208478", "image" => "Adnan.png"],
    "Lenea Contreras" => ["languages" => "( English, Tagalog )", "phoneNumber" => "+971545866222", "image" => "Lenea.png"],
    "Artur Ogorodov" => ["languages" => "( English )", "phoneNumber" => "+971542792910", "image" => "Artur.png"],
    "Souad Birafane" => ["languages" => "( English, Arabic, French )", "phoneNumber" => "+971542473919", "image" => "Souad.png"],
);

$businessActivity = [
    'businessActivity1',
    'businessActivity2',
    'businessActivity3',
    'businessActivity4',
    'businessActivity5',
    'businessActivity6',
    'businessActivity7',
    'businessActivity8',
    'businessActivity9',
    'businessActivity10',
    'businessActivity11',
    'businessActivity12',
    'businessActivity13',
    'businessActivity14',
    'businessActivity15',
    'businessActivity16',
    'businessActivity17',
    'businessActivity18',
    'businessActivity19',
    'businessActivity20',
    'businessActivity21',
    'businessActivity22',
    'businessActivity23',
    'businessActivity24',
    'businessActivity25',
    'businessActivity26',
    'businessActivity27',
    'businessActivity28',
    'businessActivity29',
    'businessActivity30',
    'businessActivity31',
    'businessActivity32',
    'businessActivity33',
    'businessActivity34',
    'businessActivity35',
    'businessActivity36',
    'businessActivity37',
    'businessActivity38',
    'businessActivity39',
    'businessActivity40',
    'businessActivity41',
    'businessActivity42',
];

$premises = [
    'premises1',
    'premises2',
    'premises3',
    'premises4',
    'premises5'
];

$countryDetails = array(
    "United Arab Emirates" => ["code" => "AE", "ISO3166" => "ARE", "phoneCode" => "+971", "flag" => "🇦🇪", "currencyCode" => "AED"],
    "Afghanistan" => ["code" => "AF", "ISO3166" => "AFG", "phoneCode" => "+93", "flag" => "🇦🇫", "currencyCode" => "AFN"],
    "Albania" => ["code" => "AL", "ISO3166" => "ALB", "phoneCode" => "+355", "flag" => "🇦🇱", "currencyCode" => "ALL"],
    "Algeria" => ["code" => "DZ", "ISO3166" => "DZA", "phoneCode" => "+213", "flag" => "🇩🇿", "currencyCode" => "DZD"],
    "American Samoa" => ["code" => "AS", "ISO3166" => "ASM", "phoneCode" => "+1 684", "flag" => "🇦🇸", "currencyCode" => "USD"],
    "Andorra" => ["code" => "AD", "ISO3166" => "AND", "phoneCode" => "+376", "flag" => "🇦🇩", "currencyCode" => "EUR"],
    "Angola" => ["code" => "AO", "ISO3166" => "AGO", "phoneCode" => "+244", "flag" => "🇦🇴", "currencyCode" => "AOA"],
    "Anguilla" => ["code" => "AI", "ISO3166" => "AIA", "phoneCode" => "+1 264", "flag" => "🇦🇮", "currencyCode" => "XCD"],
    "Antarctica" => ["code" => "AQ", "ISO3166" => "ATA", "phoneCode" => "+672, 64", "flag" => "🇦🇶", "currencyCode" => null],
    "Antigua and Barbuda" => ["code" => "AG", "ISO3166" => "ATG", "phoneCode" => "+1 268", "flag" => "🇦🇬", "currencyCode" => "XCD"],
    "Argentina" => ["code" => "AR", "ISO3166" => "ARG", "phoneCode" => "+54", "flag" => "🇦🇷", "currencyCode" => "ARS"],
    "Armenia" => ["code" => "AM", "ISO3166" => "ARM", "phoneCode" => "+374", "flag" => "🇦🇲", "currencyCode" => "AMD"],
    "Aruba" => ["code" => "AW", "ISO3166" => "ABW", "phoneCode" => "+297", "flag" => "🇦🇼", "currencyCode" => "AWG"],
    "Ascension Island" => ["code" => "AC/ASC", "ISO3166" => "ASC", "phoneCode" => "+247", "flag" => "🇦🇨", "currencyCode" => null],
    "Australia" => ["code" => "AU", "ISO3166" => "AUS", "phoneCode" => "+61", "flag" => "🇦🇺", "currencyCode" => "AUD"],
    "Austria" => ["code" => "AT", "ISO3166" => "AUT", "phoneCode" => "+43", "flag" => "🇦🇹", "currencyCode" => "EUR"],
    "Azerbaijan" => ["code" => "AZ", "ISO3166" => "AZE", "phoneCode" => "+994", "flag" => "🇦🇿", "currencyCode" => "AZN"],
    "Bahamas" => ["code" => "BS", "ISO3166" => "BHS", "phoneCode" => "+1 242", "flag" => "🇧🇸", "currencyCode" => "BSD"],
    "Bahrain" => ["code" => "BH", "ISO3166" => "BHR", "phoneCode" => "+973", "flag" => "🇧🇭", "currencyCode" => "BHD"],
    "Bangladesh" => ["code" => "BD", "ISO3166" => "BGD", "phoneCode" => "+880", "flag" => "🇧🇩", "currencyCode" => "BDT"],
    "Barbados" => ["code" => "BB", "ISO3166" => "BRB", "phoneCode" => "+1 246", "flag" => "🇧🇧", "currencyCode" => "BBD"],
    "Belarus" => ["code" => "BY", "ISO3166" => "BLR", "phoneCode" => "+375", "flag" => "🇧🇾", "currencyCode" => "BYN"],
    "Belgium" => ["code" => "BE", "ISO3166" => "BEL", "phoneCode" => "+32", "flag" => "🇧🇪", "currencyCode" => "EUR"],
    "Belize" => ["code" => "BZ", "ISO3166" => "BLZ", "phoneCode" => "+501", "flag" => "🇧🇿", "currencyCode" => "BZD"],
    "Benin" => ["code" => "BJ", "ISO3166" => "BEN", "phoneCode" => "+229", "flag" => "🇧🇯", "currencyCode" => "XOF"],
    "Bermuda" => ["code" => "BM", "ISO3166" => "BMU", "phoneCode" => "+1 441", "flag" => "🇧🇲", "currencyCode" => "BMD"],
    "Bhutan" => ["code" => "BT", "ISO3166" => "BTN", "phoneCode" => "+975", "flag" => "🇧🇹", "currencyCode" => "BTN"],
    "Bolivia" => ["code" => "BO", "ISO3166" => "BOL", "phoneCode" => "+591", "flag" => "🇧🇴", "currencyCode" => "BOB"],
    "Bosnia and Herzegovina" => ["code" => "BA", "ISO3166" => "BIH", "phoneCode" => "+387", "flag" => "🇧🇦", "currencyCode" => "BAM"],
    "Botswana" => ["code" => "BW", "ISO3166" => "BWA", "phoneCode" => "+267", "flag" => "🇧🇼", "currencyCode" => "BWP"],
    "Brazil" => ["code" => "BR", "ISO3166" => "BRA", "phoneCode" => "+55", "flag" => "🇧🇷", "currencyCode" => "BRL"],

    "British Virgin Islands" => ["code" => "VG", "ISO3166" => "VGB", "phoneCode" => "+1 284", "flag" => "🇻🇬", "currencyCode" => "USD"],
    "Brunei" => ["code" => "BN", "ISO3166" => "BRN", "phoneCode" => "+673", "flag" => "🇧🇳", "currencyCode" => "BND"],
    "Bulgaria" => ["code" => "BG", "ISO3166" => "BGR", "phoneCode" => "+359", "flag" => "🇧🇬", "currencyCode" => "BGN"],
    "Burkina Faso" => ["code" => "BF", "ISO3166" => "BFA", "phoneCode" => "+226", "flag" => "🇧🇫", "currencyCode" => "XOF"],
    "Burma (Myanmar)" => ["code" => "MM", "ISO3166" => "MMR", "phoneCode" => "+95", "flag" => "🇲🇲", "currencyCode" => "MMK"],
    "Burundi" => ["code" => "BI", "ISO3166" => "BDI", "phoneCode" => "+257", "flag" => "🇧🇮", "currencyCode" => "BIF"],
    "Cambodia" => ["code" => "KH", "ISO3166" => "KHM", "phoneCode" => "+855", "flag" => "🇰🇭", "currencyCode" => "KHR"],
    "Cameroon" => ["code" => "CM", "ISO3166" => "CMR", "phoneCode" => "+237", "flag" => "🇨🇲", "currencyCode" => "XAF"],
    "Canada" => ["code" => "CA", "ISO3166" => "CAN", "phoneCode" => "+1", "flag" => "🇨🇦", "currencyCode" => "CAD"],
    "Cape Verde" => ["code" => "CV", "ISO3166" => "CPV", "phoneCode" => "+238", "flag" => "🇨🇻", "currencyCode" => "CVE"],
    "Cayman Islands" => ["code" => "KY", "ISO3166" => "CYM", "phoneCode" => "+1 345", "flag" => "🇰🇾", "currencyCode" => "KYD"],
    "Central African Republic" => ["code" => "CF", "ISO3166" => "CAF", "phoneCode" => "+236", "flag" => "🇨🇫", "currencyCode" => "XAF"],
    "Chad" => ["code" => "TD", "ISO3166" => "TCD", "phoneCode" => "+235", "flag" => "🇹🇩", "currencyCode" => "XAF"],
    "Chile" => ["code" => "CL", "ISO3166" => "CHL", "phoneCode" => "+56", "flag" => "🇨🇱", "currencyCode" => "CLP"],
    "China" => ["code" => "CN", "ISO3166" => "CHN", "phoneCode" => "+86", "flag" => "🇨🇳", "currencyCode" => "CNY"],
    "Christmas Island" => ["code" => "CX", "ISO3166" => "CXR", "phoneCode" => "+61", "flag" => "🇨🇽", "currencyCode" => "AUD"],
    "Cocos (Keeling) Islands" => ["code" => "CC", "ISO3166" => "CCK", "phoneCode" => "+61", "flag" => "🇨🇨", "currencyCode" => "AUD"],
    "Colombia" => ["code" => "CO", "ISO3166" => "COL", "phoneCode" => "+57", "flag" => "🇨🇴", "currencyCode" => "COP"],
    "Comoros" => ["code" => "KM", "ISO3166" => "COM", "phoneCode" => "+269", "flag" => "🇰🇲", "currencyCode" => "KMF"],
    "Congo" => ["code" => "CG", "ISO3166" => "COG", "phoneCode" => "+242", "flag" => "🇨🇬", "currencyCode" => "XAF"],
    "Cook Islands" => ["code" => "CK", "ISO3166" => "COK", "phoneCode" => "+682", "flag" => "🇨🇰", "currencyCode" => "NZD"],
    "Costa Rica" => ["code" => "CR", "ISO3166" => "CRC", "phoneCode" => "+506", "flag" => "🇨🇷", "currencyCode" => "CRC"],
    "Croatia" => ["code" => "HR", "ISO3166" => "HRV", "phoneCode" => "+385", "flag" => "🇭🇷", "currencyCode" => "HRK"],
    "Cuba" => ["code" => "CU", "ISO3166" => "CUB", "phoneCode" => "+53", "flag" => "🇨🇺", "currencyCode" => "CUP"],
    "Cyprus" => ["code" => "CY", "ISO3166" => "CYP", "phoneCode" => "+357", "flag" => "🇨🇾", "currencyCode" => "EUR"],
    "Czech Republic" => ["code" => "CZ", "ISO3166" => "CZE", "phoneCode" => "+420", "flag" => "🇨🇿", "currencyCode" => "CZK"],
    "Democratic Republic of the Congo" => ["code" => "CD", "ISO3166" => "COD", "phoneCode" => "+243", "flag" => "🇨🇩", "currencyCode" => "CDF"],
    "Denmark" => ["code" => "DK", "ISO3166" => "DNK", "phoneCode" => "+45", "flag" => "🇩🇰", "currencyCode" => "DKK"],
    "Diego Garcia" => ["code" => "DG/DGA", "ISO3166" => "DGA", "phoneCode" => "+246", "flag" => "🇩🇬", "currencyCode" => "USD"],
    "Djibouti" => ["code" => "DJ", "ISO3166" => "DJI", "phoneCode" => "+253", "flag" => "🇩🇯", "currencyCode" => "DJF"],
    "Dominica" => ["code" => "DM", "ISO3166" => "DMA", "phoneCode" => "+1 767", "flag" => "🇩🇲", "currencyCode" => "XCD"],
    "Dominican Republic" => ["code" => "DO", "ISO3166" => "DOM", "phoneCode" => "+1 809, 1 829, 1 849", "flag" => "🇩🇴", "currencyCode" => "DOP"],
    "Ecuador" => ["code" => "EC", "ISO3166" => "ECU", "phoneCode" => "+593", "flag" => "🇪🇨", "currencyCode" => "USD"],

    "Egypt" => ["code" => "EG", "ISO3166" => "EGY", "phoneCode" => "+20", "flag" => "🇪🇬", "currencyCode" => "EGP"],
    "El Salvador" => ["code" => "SV", "ISO3166" => "SLV", "phoneCode" => "+503", "flag" => "🇸🇻", "currencyCode" => "USD"],
    "Equatorial Guinea" => ["code" => "GQ", "ISO3166" => "GNQ", "phoneCode" => "+240", "flag" => "🇬🇶", "currencyCode" => "XAF"],
    "Eritrea" => ["code" => "ER", "ISO3166" => "ERI", "phoneCode" => "+291", "flag" => "🇪🇷", "currencyCode" => "ERN"],
    "Estonia" => ["code" => "EE", "ISO3166" => "EST", "phoneCode" => "+372", "flag" => "🇪🇪", "currencyCode" => "EUR"],
    "Ethiopia" => ["code" => "ET", "ISO3166" => "ETH", "phoneCode" => "+251", "flag" => "🇪🇹", "currencyCode" => "ETB"],
    "Falkland Islands" => ["code" => "FK", "ISO3166" => "FLK", "phoneCode" => "+500", "flag" => "🇫🇰", "currencyCode" => "FKP"],
    "Faroe Islands" => ["code" => "FO", "ISO3166" => "FRO", "phoneCode" => "+298", "flag" => "🇫🇴", "currencyCode" => "DKK"],
    "Fiji" => ["code" => "FJ", "ISO3166" => "FJI", "phoneCode" => "+679", "flag" => "🇫🇯", "currencyCode" => "FJD"],
    "Finland" => ["code" => "FI", "ISO3166" => "FIN", "phoneCode" => "+358", "flag" => "🇫🇮", "currencyCode" => "EUR"],
    "France" => ["code" => "FR", "ISO3166" => "FRA", "phoneCode" => "+33", "flag" => "🇫🇷", "currencyCode" => "EUR"],
    "French Guiana" => ["code" => "GF", "ISO3166" => "GUF", "phoneCode" => "+594", "flag" => "🇬🇫", "currencyCode" => "EUR"],
    "French Polynesia" => ["code" => "PF", "ISO3166" => "PYF", "phoneCode" => "+689", "flag" => "🇵🇫", "currencyCode" => "XPF"],
    "Gabon" => ["code" => "GA", "ISO3166" => "GAB", "phoneCode" => "+241", "flag" => "🇬🇦", "currencyCode" => "XAF"],
    "Gambia" => ["code" => "GM", "ISO3166" => "GMB", "phoneCode" => "+220", "flag" => "🇬🇲", "currencyCode" => "GMD"],
    "Georgia" => ["code" => "GE", "ISO3166" => "GEO", "phoneCode" => "+995", "flag" => "🇬🇪", "currencyCode" => "GEL"],
    "Germany" => ["code" => "DE", "ISO3166" => "DEU", "phoneCode" => "+49", "flag" => "🇩🇪", "currencyCode" => "EUR"],
    "Ghana" => ["code" => "GH", "ISO3166" => "GHA", "phoneCode" => "+233", "flag" => "🇬🇭", "currencyCode" => "GHS"],
    "Gibraltar" => ["code" => "GI", "ISO3166" => "GIB", "phoneCode" => "+350", "flag" => "🇬🇮", "currencyCode" => "GIP"],
    "Greece" => ["code" => "GR", "ISO3166" => "GRC", "phoneCode" => "+30", "flag" => "🇬🇷", "currencyCode" => "EUR"],
    "Greenland" => ["code" => "GL", "ISO3166" => "GRL", "phoneCode" => "+299", "flag" => "🇬🇱", "currencyCode" => "DKK"],
    "Grenada" => ["code" => "GD", "ISO3166" => "GRD", "phoneCode" => "+1 473", "flag" => "🇬🇩", "currencyCode" => "XCD"],
    "Guadeloupe" => ["code" => "GP", "ISO3166" => "GLP", "phoneCode" => "+590", "flag" => "🇬🇵", "currencyCode" => "EUR"],
    "Guam" => ["code" => "GU", "ISO3166" => "GUM", "phoneCode" => "+1 671", "flag" => "🇬🇺", "currencyCode" => "USD"],
    "Guatemala" => ["code" => "GT", "ISO3166" => "GTM", "phoneCode" => "+502", "flag" => "🇬🇹", "currencyCode" => "GTQ"],
    "Guinea" => ["code" => "GN", "ISO3166" => "GIN", "phoneCode" => "+224", "flag" => "🇬🇳", "currencyCode" => "GNF"],
    "Guinea-Bissau" => ["code" => "GW", "ISO3166" => "GNB", "phoneCode" => "+245", "flag" => "🇬🇼", "currencyCode" => "XOF"],
    "Guyana" => ["code" => "GY", "ISO3166" => "GUY", "phoneCode" => "+592", "flag" => "🇬🇾", "currencyCode" => "GYD"],
    "Haiti" => ["code" => "HT", "ISO3166" => "HTI", "phoneCode" => "+509", "flag" => "🇭🇹", "currencyCode" => "HTG"],
    "Holy See (Vatican City)" => ["code" => "VA", "ISO3166" => "VAT", "phoneCode" => "+39", "flag" => "🇻🇦", "currencyCode" => "EUR"],
    "Honduras" => ["code" => "HN", "ISO3166" => "HND", "phoneCode" => "+504", "flag" => "🇭🇳", "currencyCode" => "HNL"],
    "Hong Kong" => ["code" => "HK", "ISO3166" => "HKG", "phoneCode" => "+852", "flag" => "🇭🇰", "currencyCode" => "HKD"],
    "Hungary" => ["code" => "HU", "ISO3166" => "HUN", "phoneCode" => "+36", "flag" => "🇭🇺", "currencyCode" => "HUF"],
    "Iceland" => ["code" => "IS", "ISO3166" => "IS", "phoneCode" => "+354", "flag" => "🇮🇸", "currencyCode" => "ISK"],
    "India" => ["code" => "IN", "ISO3166" => "IND", "phoneCode" => "+91", "flag" => "🇮🇳", "currencyCode" => "INR"],
    "Indonesia" => ["code" => "ID", "ISO3166" => "IDN", "phoneCode" => "+62", "flag" => "🇮🇩", "currencyCode" => "IDR"],
    "Iran" => ["code" => "IR", "ISO3166" => "IRN", "phoneCode" => "+98", "flag" => "🇮🇷", "currencyCode" => "IRR"],
    "Iraq" => ["code" => "IQ", "ISO3166" => "IRQ", "phoneCode" => "+964", "flag" => "🇮🇶", "currencyCode" => "IQD"],
    "Ireland" => ["code" => "IE", "ISO3166" => "IRL", "phoneCode" => "+353", "flag" => "🇮🇪", "currencyCode" => "EUR"],
    "Isle of Man" => ["code" => "IM", "ISO3166" => "IMN", "phoneCode" => "+44", "flag" => "🇮🇲", "currencyCode" => "GBP"],
    "Israel" => ["code" => "IL", "ISO3166" => "ISR", "phoneCode" => "+972", "flag" => "🇮🇱", "currencyCode" => "ILS"],
    "Italy" => ["code" => "IT", "ISO3166" => "ITA", "phoneCode" => "+39", "flag" => "🇮🇹", "currencyCode" => "EUR"],
    "Ivory Coast (Côte d'Ivoire)" => ["code" => "CI", "ISO3166" => "CIV", "phoneCode" => "+225", "flag" => "🇨🇮", "currencyCode" => "XOF"],
    "Jamaica" => ["code" => "JM", "ISO3166" => "JAM", "phoneCode" => "+1 876", "flag" => "🇯🇲", "currencyCode" => "JMD"],

    "Japan" => ["code" => "JP", "ISO3166" => "JPN", "phoneCode" => "+81", "flag" => "🇯🇵", "currencyCode" => "JPY"],
    "Jersey" => ["code" => "JE", "ISO3166" => "JEY", "phoneCode" => "+44", "flag" => "🇯🇪", "currencyCode" => "GBP"],
    "Jordan" => ["code" => "JO", "ISO3166" => "JOR", "phoneCode" => "+962", "flag" => "🇯🇴", "currencyCode" => "JOD"],
    "Kazakhstan" => ["code" => "KZ", "ISO3166" => "KAZ", "phoneCode" => "+7", "flag" => "🇰🇿", "currencyCode" => "KZT"],
    "Kenya" => ["code" => "KE", "ISO3166" => "KEN", "phoneCode" => "+254", "flag" => "🇰🇪", "currencyCode" => "KES"],
    "Kiribati" => ["code" => "KI", "ISO3166" => "KIR", "phoneCode" => "+686", "flag" => "🇰🇮", "currencyCode" => "AUD"],
    "Kuwait" => ["code" => "KW", "ISO3166" => "KWT", "phoneCode" => "+965", "flag" => "🇰🇼", "currencyCode" => "KWD"],
    "Kyrgyzstan" => ["code" => "KG", "ISO3166" => "KGZ", "phoneCode" => "+996", "flag" => "🇰🇬", "currencyCode" => "KGS"],
    "Laos" => ["code" => "LA", "ISO3166" => "LAO", "phoneCode" => "+856", "flag" => "🇱🇦", "currencyCode" => "LAK"],
    "Latvia" => ["code" => "LV", "ISO3166" => "LVA", "phoneCode" => "+371", "flag" => "🇱🇻", "currencyCode" => "EUR"],
    "Lebanon" => ["code" => "LB", "ISO3166" => "LBN", "phoneCode" => "+961", "flag" => "🇱🇧", "currencyCode" => "LBP"],
    "Lesotho" => ["code" => "LS", "ISO3166" => "LSO", "phoneCode" => "+266", "flag" => "🇱🇸", "currencyCode" => "LSL"],
    "Liberia" => ["code" => "LR", "ISO3166" => "LBR", "phoneCode" => "+231", "flag" => "🇱🇷", "currencyCode" => "LRD"],
    "Libya" => ["code" => "LY", "ISO3166" => "LBY", "phoneCode" => "+218", "flag" => "🇱🇾", "currencyCode" => "LYD"],
    "Liechtenstein" => ["code" => "LI", "ISO3166" => "LIE", "phoneCode" => "+423", "flag" => "🇱🇮", "currencyCode" => "CHF"],
    "Lithuania" => ["code" => "LT", "ISO3166" => "LTU", "phoneCode" => "+370", "flag" => "🇱🇹", "currencyCode" => "EUR"],
    "Luxembourg" => ["code" => "LU", "ISO3166" => "LUX", "phoneCode" => "+352", "flag" => "🇱🇺", "currencyCode" => "EUR"],
    "Macau" => ["code" => "MO", "ISO3166" => "MAC", "phoneCode" => "+853", "flag" => "🇲🇴", "currencyCode" => "MOP"],
    "Macedonia" => ["code" => "MK", "ISO3166" => "MKD", "phoneCode" => "+389", "flag" => "🇲🇰", "currencyCode" => "MKD"],
    "Madagascar" => ["code" => "MG", "ISO3166" => "MDG", "phoneCode" => "+261", "flag" => "🇲🇬", "currencyCode" => "MGA"],
    "Malawi" => ["code" => "MW", "ISO3166" => "MWI", "phoneCode" => "+265", "flag" => "🇲🇼", "currencyCode" => "MWK"],
    "Malaysia" => ["code" => "MY", "ISO3166" => "MYS", "phoneCode" => "+60", "flag" => "🇲🇾", "currencyCode" => "MYR"],
    "Maldives" => ["code" => "MV", "ISO3166" => "MDV", "phoneCode" => "+960", "flag" => "🇲🇻", "currencyCode" => "MVR"],
    "Mali" => ["code" => "ML", "ISO3166" => "MLI", "phoneCode" => "+223", "flag" => "🇲🇱", "currencyCode" => "XOF"],
    "Malta" => ["code" => "MT", "ISO3166" => "MLT", "phoneCode" => "+356", "flag" => "🇲🇹", "currencyCode" => "EUR"],
    "Marshall Islands" => ["code" => "MH", "ISO3166" => "MHL", "phoneCode" => "+692", "flag" => "🇲🇭", "currencyCode" => "USD"],
    "Martinique" => ["code" => "MQ", "ISO3166" => "MTQ", "phoneCode" => "+596", "flag" => "🇲🇶", "currencyCode" => "EUR"],
    "Mauritania" => ["code" => "MR", "ISO3166" => "MRT", "phoneCode" => "+222", "flag" => "🇲🇷", "currencyCode" => "MRU"],
    "Mauritius" => ["code" => "MU", "ISO3166" => "MUS", "phoneCode" => "+230", "flag" => "🇲🇺", "currencyCode" => "MUR"],
    "Mayotte" => ["code" => "YT", "ISO3166" => "MYT", "phoneCode" => "+262", "flag" => "🇾🇹", "currencyCode" => "EUR"],
    "Mexico" => ["code" => "MX", "ISO3166" => "MEX", "phoneCode" => "+52", "flag" => "🇲🇽", "currencyCode" => "MXN"],

    "Micronesia" => ["code" => "FM", "ISO3166" => "FSM", "phoneCode" => "+691", "flag" => "🇫🇲", "currencyCode" => "USD"],
    "Moldova" => ["code" => "MD", "ISO3166" => "MDA", "phoneCode" => "+373", "flag" => "🇲🇩", "currencyCode" => "MDL"],
    "Monaco" => ["code" => "MC", "ISO3166" => "MCO", "phoneCode" => "+377", "flag" => "🇲🇨", "currencyCode" => "EUR"],
    "Mongolia" => ["code" => "MN", "ISO3166" => "MNG", "phoneCode" => "+976", "flag" => "🇲🇳", "currencyCode" => "MNT"],
    "Montenegro" => ["code" => "ME", "ISO3166" => "MNE", "phoneCode" => "+382", "flag" => "🇲🇪", "currencyCode" => "EUR"],
    "Montserrat" => ["code" => "MS", "ISO3166" => "MSR", "phoneCode" => "+1 664", "flag" => "🇲🇸", "currencyCode" => "XCD"],
    "Morocco" => ["code" => "MA", "ISO3166" => "MAR", "phoneCode" => "+212", "flag" => "🇲🇦", "currencyCode" => "MAD"],
    "Mozambique" => ["code" => "MZ", "ISO3166" => "MOZ", "phoneCode" => "+258", "flag" => "🇲🇿", "currencyCode" => "MZN"],
    "Namibia" => ["code" => "NA", "ISO3166" => "NAM", "phoneCode" => "+264", "flag" => "🇳🇦", "currencyCode" => "NAD"],
    "Nauru" => ["code" => "NR", "ISO3166" => "NRU", "phoneCode" => "+674", "flag" => "🇳🇷", "currencyCode" => "AUD"],
    "Nepal" => ["code" => "NP", "ISO3166" => "NPL", "phoneCode" => "+977", "flag" => "🇳🇵", "currencyCode" => "NPR"],
    "Netherlands" => ["code" => "NL", "ISO3166" => "NLD", "phoneCode" => "+31", "flag" => "🇳🇱", "currencyCode" => "EUR"],
    "Netherlands Antilles" => ["code" => "AN", "ISO3166" => "ANT", "phoneCode" => "+599", "flag" => "🇳🇱", "currencyCode" => "ANG"],
    "New Caledonia" => ["code" => "NC", "ISO3166" => "NCL", "phoneCode" => "+687", "flag" => "🇳🇨", "currencyCode" => "XPF"],
    "New Zealand" => ["code" => "NZ", "ISO3166" => "NZL", "phoneCode" => "+64", "flag" => "🇳🇿", "currencyCode" => "NZD"],
    "Nicaragua" => ["code" => "NI", "ISO3166" => "NIC", "phoneCode" => "+505", "flag" => "🇳🇮", "currencyCode" => "NIO"],
    "Niger" => ["code" => "NE", "ISO3166" => "NER", "phoneCode" => "+227", "flag" => "🇳🇪", "currencyCode" => "XOF"],
    "Nigeria" => ["code" => "NG", "ISO3166" => "NGA", "phoneCode" => "+234", "flag" => "🇳🇬", "currencyCode" => "NGN"],
    "Niue" => ["code" => "NU", "ISO3166" => "NIU", "phoneCode" => "+683", "flag" => "🇳🇺", "currencyCode" => "NZD"],
    "Norfolk Island" => ["code" => "NF", "ISO3166" => "NFK", "phoneCode" => "+672", "flag" => "🇳🇫", "currencyCode" => "AUD"],
    "North Korea" => ["code" => "KP", "ISO3166" => "PRK", "phoneCode" => "+850", "flag" => "🇰🇵", "currencyCode" => "KPW"],
    "Northern Mariana Islands" => ["code" => "MP", "ISO3166" => "MNP", "phoneCode" => "+1 670", "flag" => "🇲🇵", "currencyCode" => "USD"],
    "Norway" => ["code" => "NO", "ISO3166" => "NOR", "phoneCode" => "+47", "flag" => "🇳🇴", "currencyCode" => "NOK"],
    "Oman" => ["code" => "OM", "ISO3166" => "OMN", "phoneCode" => "+968", "flag" => "🇴🇲", "currencyCode" => "OMR"],
    "Pakistan" => ["code" => "PK", "ISO3166" => "PAK", "phoneCode" => "+92", "flag" => "🇵🇰", "currencyCode" => "PKR"],
    "Palau" => ["code" => "PW", "ISO3166" => "PLW", "phoneCode" => "+680", "flag" => "🇵🇼", "currencyCode" => "USD"],
    "Palestine" => ["code" => "PS", "ISO3166" => "PSE", "phoneCode" => "+970", "flag" => "🇵🇸", "currencyCode" => "ILS"],
    "Panama" => ["code" => "PA", "ISO3166" => "PAN", "phoneCode" => "+507", "flag" => "🇵🇦", "currencyCode" => "PAB"],
    "Papua New Guinea" => ["code" => "PG", "ISO3166" => "PNG", "phoneCode" => "+675", "flag" => "🇵🇬", "currencyCode" => "PGK"],
    "Paraguay" => ["code" => "PY", "ISO3166" => "PRY", "phoneCode" => "+595", "flag" => "🇵🇾", "currencyCode" => "PYG"],
    "Peru" => ["code" => "PE", "ISO3166" => "PER", "phoneCode" => "+51", "flag" => "🇵🇪", "currencyCode" => "PEN"],
    "Philippines" => ["code" => "PH", "ISO3166" => "PHL", "phoneCode" => "+63", "flag" => "🇵🇭", "currencyCode" => "PHP"],
    "Pitcairn Islands" => ["code" => "PN", "ISO3166" => "PCN", "phoneCode" => "+870", "flag" => "🇵🇳", "currencyCode" => "NZD"],
    "Poland" => ["code" => "PL", "ISO3166" => "POL", "phoneCode" => "+48", "flag" => "🇵🇱", "currencyCode" => "PLN"],
    "Portugal" => ["code" => "PT", "ISO3166" => "PRT", "phoneCode" => "+351", "flag" => "🇵🇹", "currencyCode" => "EUR"],
    "Puerto Rico" => ["code" => "PR", "ISO3166" => "PRI", "phoneCode" => "+1 787, 1 939", "flag" => "🇵🇷", "currencyCode" => "USD"],
    "Qatar" => ["code" => "QA", "ISO3166" => "QAT", "phoneCode" => "+974", "flag" => "🇶🇦", "currencyCode" => "QAR"],
    "Republic of the Congo" => ["code" => "CG", "ISO3166" => "COG", "phoneCode" => "+242", "flag" => "🇨🇬", "currencyCode" => "XAF"],
    "Reunion Island" => ["code" => "RE", "ISO3166" => "REU", "phoneCode" => "+262", "flag" => "🇷🇪", "currencyCode" => "EUR"],
    "Romania" => ["code" => "RO", "ISO3166" => "ROU", "phoneCode" => "+40", "flag" => "🇷🇴", "currencyCode" => "RON"],

    "Russia" => ["code" => "RU", "ISO3166" => "RUS", "phoneCode" => "+7", "flag" => "🇷🇺", "currencyCode" => "RUB"],
    "Rwanda" => ["code" => "RW", "ISO3166" => "RWA", "phoneCode" => "+250", "flag" => "🇷🇼", "currencyCode" => "RWF"],
    "Saint Barthelemy" => ["code" => "BL", "ISO3166" => "BLM", "phoneCode" => "+590", "flag" => "🇧🇱", "currencyCode" => "EUR"],
    "Saint Helena" => ["code" => "SH", "ISO3166" => "SHN", "phoneCode" => "+290", "flag" => "🇸🇭", "currencyCode" => "SHP"],
    "Saint Kitts and Nevis" => ["code" => "KN", "ISO3166" => "KNA", "phoneCode" => "+1 869", "flag" => "🇰🇳", "currencyCode" => "XCD"],
    "Saint Lucia" => ["code" => "LC", "ISO3166" => "LCA", "phoneCode" => "+1 758", "flag" => "🇱🇨", "currencyCode" => "XCD"],
    "Saint Martin" => ["code" => "MF", "ISO3166" => "MAF", "phoneCode" => "+590", "flag" => "🇲🇫", "currencyCode" => "EUR"],
    "Saint Pierre and Miquelon" => ["code" => "PM", "ISO3166" => "SPM", "phoneCode" => "+508", "flag" => "🇵🇲", "currencyCode" => "EUR"],
    "Saint Vincent and the Grenadines" => ["code" => "VC", "ISO3166" => "VCT", "phoneCode" => "+1 784", "flag" => "🇻🇨", "currencyCode" => "XCD"],
    "Samoa" => ["code" => "WS", "ISO3166" => "WSM", "phoneCode" => "+685", "flag" => "🇼🇸", "currencyCode" => "WST"],
    "San Marino" => ["code" => "SM", "ISO3166" => "SMR", "phoneCode" => "+378", "flag" => "🇸🇲", "currencyCode" => "EUR"],
    "Sao Tome and Principe" => ["code" => "ST", "ISO3166" => "STP", "phoneCode" => "+239", "flag" => "🇸🇹", "currencyCode" => "STN"],
    "Saudi Arabia" => ["code" => "SA", "ISO3166" => "SAU", "phoneCode" => "+966", "flag" => "🇸🇦", "currencyCode" => "SAR"],
    "Senegal" => ["code" => "SN", "ISO3166" => "SEN", "phoneCode" => "+221", "flag" => "🇸🇳", "currencyCode" => "XOF"],
    "Serbia" => ["code" => "RS", "ISO3166" => "SRB", "phoneCode" => "+381", "flag" => "🇷🇸", "currencyCode" => "RSD"],
    "Seychelles" => ["code" => "SC", "ISO3166" => "SYC", "phoneCode" => "+248", "flag" => "🇸🇨", "currencyCode" => "SCR"],
    "Sierra Leone" => ["code" => "SL", "ISO3166" => "SLE", "phoneCode" => "+232", "flag" => "🇸🇱", "currencyCode" => "SLL"],
    "Singapore" => ["code" => "SG", "ISO3166" => "SGP", "phoneCode" => "+65", "flag" => "🇸🇬", "currencyCode" => "SGD"],
    "Sint Maarten" => ["code" => "SX", "ISO3166" => "SXM", "phoneCode" => "+1 721", "flag" => "🇸🇽", "currencyCode" => "ANG"],
    "Slovakia" => ["code" => "SK", "ISO3166" => "SVK", "phoneCode" => "+421", "flag" => "🇸🇰", "currencyCode" => "EUR"],
    "Slovenia" => ["code" => "SI", "ISO3166" => "SVN", "phoneCode" => "+386", "flag" => "🇸🇮", "currencyCode" => "EUR"],
    "Solomon Islands" => ["code" => "SB", "ISO3166" => "SLB", "phoneCode" => "+677", "flag" => "🇸🇧", "currencyCode" => "SBD"],
    "Somalia" => ["code" => "SO", "ISO3166" => "SOM", "phoneCode" => "+252", "flag" => "🇸🇴", "currencyCode" => "SOS"],
    "South Africa" => ["code" => "ZA", "ISO3166" => "ZAF", "phoneCode" => "+27", "flag" => "🇿🇦", "currencyCode" => "ZAR"],
    "South Korea" => ["code" => "KR", "ISO3166" => "KOR", "phoneCode" => "+82", "flag" => "🇰🇷", "currencyCode" => "KRW"],
    "South Sudan" => ["code" => "SS", "ISO3166" => "SSD", "phoneCode" => "+211", "flag" => "🇸🇸", "currencyCode" => "SSP"],
    "Spain" => ["code" => "ES", "ISO3166" => "ESP", "phoneCode" => "+34", "flag" => "🇪🇸", "currencyCode" => "EUR"],
    "Sri Lanka" => ["code" => "LK", "ISO3166" => "LKA", "phoneCode" => "+94", "flag" => "🇱🇰", "currencyCode" => "LKR"],
    "Sudan" => ["code" => "SD", "ISO3166" => "SDN", "phoneCode" => "+249", "flag" => "🇸🇩", "currencyCode" => "SDG"],
    "Suriname" => ["code" => "SR", "ISO3166" => "SUR", "phoneCode" => "+597", "flag" => "🇸🇷", "currencyCode" => "SRD"],
    "Svalbard" => ["code" => "SJ", "ISO3166" => "SJM", "phoneCode" => "+47", "flag" => "🇸🇯", "currencyCode" => "NOK"],
    "Swaziland" => ["code" => "SZ", "ISO3166" => "SWZ", "phoneCode" => "+268", "flag" => "🇸🇿", "currencyCode" => "SZL"],
    "Sweden" => ["code" => "SE", "ISO3166" => "SWE", "phoneCode" => "+46", "flag" => "🇸🇪", "currencyCode" => "SEK"],
    "Switzerland" => ["code" => "CH", "ISO3166" => "CHE", "phoneCode" => "+41", "flag" => "🇨🇭", "currencyCode" => "CHF"],
    "Syria" => ["code" => "SY", "ISO3166" => "SYR", "phoneCode" => "+963", "flag" => "🇸🇾", "currencyCode" => "SYP"],
    "Taiwan" => ["code" => "TW", "ISO3166" => "TWN", "phoneCode" => "+886", "flag" => "🇹🇼", "currencyCode" => "TWD"],
    "Tajikistan" => ["code" => "TJ", "ISO3166" => "TJK", "phoneCode" => "+992", "flag" => "🇹🇯", "currencyCode" => "TJS"],
    "Tanzania" => ["code" => "TZ", "ISO3166" => "TZA", "phoneCode" => "+255", "flag" => "🇹🇿", "currencyCode" => "TZS"],
    "Thailand" => ["code" => "TH", "ISO3166" => "THA", "phoneCode" => "+66", "flag" => "🇹🇭", "currencyCode" => "THB"],
    "Timor-Leste (East Timor)" => ["code" => "TL", "ISO3166" => "TLS", "phoneCode" => "+670", "flag" => "🇹🇱", "currencyCode" => "USD"],
    "Togo" => ["code" => "TG", "ISO3166" => "TGO", "phoneCode" => "+228", "flag" => "🇹🇬", "currencyCode" => "XOF"],

    "Tokelau" => ["code" => "TK", "ISO3166" => "TKL", "phoneCode" => "+690", "flag" => "🇹🇰", "currencyCode" => "NZD"],
    "Tonga Islands" => ["code" => "TO", "ISO3166" => "TON", "phoneCode" => "+676", "flag" => "🇹🇴", "currencyCode" => "TOP"],
    "Trinidad and Tobago" => ["code" => "TT", "ISO3166" => "TTO", "phoneCode" => "+1 868", "flag" => "🇹🇹", "currencyCode" => "TTD"],
    "Tunisia" => ["code" => "TN", "ISO3166" => "TUN", "phoneCode" => "+216", "flag" => "🇹🇳", "currencyCode" => "TND"],
    "Turkey" => ["code" => "TR", "ISO3166" => "TUR", "phoneCode" => "+90", "flag" => "🇹🇷", "currencyCode" => "TRY"],
    "Turkmenistan" => ["code" => "TM", "ISO3166" => "TKM", "phoneCode" => "+993", "flag" => "🇹🇲", "currencyCode" => "TMT"],
    "Turks and Caicos Islands" => ["code" => "TC", "ISO3166" => "TCA", "phoneCode" => "+1 649", "flag" => "🇹🇨", "currencyCode" => "USD"],
    "Tuvalu" => ["code" => "TV", "ISO3166" => "TUV", "phoneCode" => "+688", "flag" => "🇹🇻", "currencyCode" => "AUD"],
    "Uganda" => ["code" => "UG", "ISO3166" => "UGA", "phoneCode" => "+256", "flag" => "🇺🇬", "currencyCode" => "UGX"],
    "Ukraine" => ["code" => "UA", "ISO3166" => "UKR", "phoneCode" => "+380", "flag" => "🇺🇦", "currencyCode" => "UAH"],
    "United Kingdom" => ["code" => "GB", "ISO3166" => "GBR", "phoneCode" => "+44", "flag" => "🇬🇧", "currencyCode" => "GBP"],
    "United States" => ["code" => "US", "ISO3166" => "USA", "phoneCode" => "+1", "flag" => "🇺🇸", "currencyCode" => "USD"],
    "Uruguay" => ["code" => "UY", "ISO3166" => "URY", "phoneCode" => "+598", "flag" => "🇺🇾", "currencyCode" => "UYU"],
    "US Virgin Islands" => ["code" => "VI", "ISO3166" => "VIR", "phoneCode" => "+1 340", "flag" => "🇻🇮", "currencyCode" => "USD"],
    "Uzbekistan" => ["code" => "UZ", "ISO3166" => "UZB", "phoneCode" => "+998", "flag" => "🇺🇿", "currencyCode" => "UZS"],
    "Vanuatu" => ["code" => "VU", "ISO3166" => "VUT", "phoneCode" => "+678", "flag" => "🇻🇺", "currencyCode" => "VUV"],
    "Venezuela" => ["code" => "VE", "ISO3166" => "VEN", "phoneCode" => "+58", "flag" => "🇻🇪", "currencyCode" => "VES"],
    "Vietnam" => ["code" => "VN", "ISO3166" => "VNM", "phoneCode" => "+84", "flag" => "🇻🇳", "currencyCode" => "VND"],
    "Wallis and Futuna" => ["code" => "WF", "ISO3166" => "WLF", "phoneCode" => "+681", "flag" => "🇼🇫", "currencyCode" => "XPF"],
    "Western Sahara" => ["code" => "EH", "ISO3166" => "ESH", "phoneCode" => "+212", "flag" => "🇪🇭", "currencyCode" => "MAD"],
    "Yemen" => ["code" => "YE", "ISO3166" => "YEM", "phoneCode" => "+967", "flag" => "🇾🇪", "currencyCode" => "YER"],
    "Zambia" => ["code" => "ZM", "ISO3166" => "ZMB", "phoneCode" => "+260", "flag" => "🇿🇲", "currencyCode" => "ZMW"],
    "Zimbabwe" => ["code" => "ZW", "ISO3166" => "ZWE", "phoneCode" => "+263", "flag" => "🇿🇼", "currencyCode" => "ZWL"],
);
$countryDetailsJson = json_encode($countryDetails);
?>